"""add failed login fields

Revision ID: 92d2ee9b4bf0
Revises: 9533fb895671
Create Date: 2026-07-14 12:43:07.255003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d2ee9b4bf0'
down_revision: Union[str, Sequence[str], None] = '9533fb895671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('users', 'refresh_token_jti')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token_jti', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###
