"""add user user_details, user_loyalty and addresses table

Revision ID: f40a52df7937
Revises: 92d2ee9b4bf0
Create Date: 2026-07-14 23:41:55.778045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f40a52df7937'
down_revision: Union[str, Sequence[str], None] = '92d2ee9b4bf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_details',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'UNDISCLOSED', name='gender'), nullable=True),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('preferred_currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('newsletter_subscribed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('marketing_opt_in', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(preferred_currency) = 3', name='ck_user_details_currency_iso_len'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_user_details_phone_number', 'user_details', ['phone_number'], unique=False, postgresql_where=sa.text('phone_number IS NOT NULL'))
    op.create_table('addresses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('user_details_id', sa.BigInteger(), nullable=False),
    sa.Column('address_type', sa.Enum('SHIPPING', 'BILLING', name='address_type'), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('line1', sa.String(length=255), nullable=False),
    sa.Column('line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(country_code) = 2', name='ck_addresses_country_iso_len'),
    sa.ForeignKeyConstraint(['user_details_id'], ['user_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('ix_addresses_user_type_active', 'addresses', ['user_details_id', 'address_type'], unique=False, postgresql_where=sa.text('is_active IS true'))
    op.create_index('uq_addresses_one_default_per_type', 'addresses', ['user_details_id', 'address_type'], unique=True, postgresql_where=sa.text('is_default IS true AND is_active IS true'))
    op.create_table('user_loyalty',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_details_id', sa.BigInteger(), nullable=False),
    sa.Column('points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tier', sa.String(length=20), server_default='bronze', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tier IN ('bronze', 'silver', 'gold', 'platinum')", name='ck_user_loyalty_tier_valid'),
    sa.CheckConstraint('points >= 0', name='ck_user_loyalty_points_non_negative'),
    sa.ForeignKeyConstraint(['user_details_id'], ['user_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_details_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_loyalty')
    op.drop_index('uq_addresses_one_default_per_type', table_name='addresses', postgresql_where=sa.text('is_default IS true AND is_active IS true'))
    op.drop_index('ix_addresses_user_type_active', table_name='addresses', postgresql_where=sa.text('is_active IS true'))
    op.drop_table('addresses')
    op.drop_index('ix_user_details_phone_number', table_name='user_details', postgresql_where=sa.text('phone_number IS NOT NULL'))
    op.drop_table('user_details')
    # ### end Alembic commands ###
